### ISSUE TITLE
use filter on plain text

### ISSUE THREAD

**Issue by danielparas** [craftcms/anchors#1]
Hi! Thanks for his plugin. By any chance is there a way to use the filter on plain text? example some similar to this:

```
<h3>{{testimonialsBlock.heading}}</h3>
{{testimonialsBlock.heading | anchor}}
```

Thanks
Daniel

**Comment by takobell** [comment]
You'd need to do something like this:

    {{ ('<h3>' ~ testimonialsBlock.heading ~ '</h3>') | anchor }}
