### ISSUE TITLE
Are there any plans to include GraphQL support?

### ISSUE THREAD

**Issue by lukew-cogapp** [craftcms/anchors#18]
Hello,

We're just wondering if there are plans to include GraphQL support for this plugin?

Otherwise, what would be your suggested approach to creating a table of contents based on headings (or manually added anchors via reactor)?

Thanks!

**Comment by brandonkelly** [comment]
Just released Anchors 3.2 (for Craft 4 only) which includes an `@anchors` GraphQL directive.

You can optionally pass `tags` and `langauge` arguments to it, just like the Twig filter.

```graphql
myRichTextField @anchars(tags: ["h1", "h2"])
```

(`tags` is `["h1", "h2", "h3"]` by default.)
