### ISSUE TITLE
Fails on headings with newlines

### ISSUE THREAD

**Issue by rungta** [craftcms/anchors#20]
### Description

The filter fails on the following:

```twig
{% apply anchors('h2') %}
  <h2>
    Hello
  </h2>
{% endapply %}
```

But works on this:

```twig
{% apply anchors('h2') %}
  <h2>Hello</h2>
{% endapply %}
```

### Additional info

- Craft version: 3.7.45
- PHP version: 7.4
- Plugins: Anchors 2.3.1

**Comment by brandonkelly** [comment]
Thanks for reporting! Anchors 2.4.0 (Craft 3) and 3.1.0 (Craft 4) have been released with a fix for this.
