### ISSUE TITLE
URL formatting issues

### ISSUE THREAD

**Issue by anita-chouhan** [craftcms/anchors#31]
### Description
Found 2 cases of URL formatting issues with the *Anchors* filter.

1. When the heading contains a word in all caps.
2. When there are quotes present in the heading.

### Usage Example:

**Header Text:**
1. Pitch FAQs
2. We'd love to hear from you

**Rendering Code:**
```
{% apply anchors('h2') %}
  <h2>Pitch FAQs</h2>
{% endapply %}
```

**For the case when a quote is present in header**
It generates two different URLs based on the rendering code
```

{% apply anchors('h2') %}
  <h2>We'd love to hear from you</h2>
{% endapply %}

Generates: /#wed-love-to-hear-from-you

{{ tag('h2', {
  text: "We'd love to hear from you",
})|anchors }}

Generates: /#we-039-d-love-to-hear-from-you
```
          
**Generated Output:**
1. .../#pitch-fAQs
2. .../#we-039-d-love-to-hear-from-you or /#wed-love-to-hear-from-you

**Expected Output:**
1. Letters should be all lowercase or in the original form as added.
2. No numeric characters in the URL.

### Additional info

- Craft version: 3.7.63.1
- PHP version: 7.4
- Plugins version: 2.4.0

**Comment by i-just** [comment]
Hi, thanks for reporting! I raised a PR.

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/anchors/pull/34 and will be included in the next release.

**Comment by anita-chouhan** [comment]
Hello @angrybrad, any updates?
