### ISSUE TITLE
Default anchorLinkTitleText not properly escaped

### ISSUE THREAD

**Issue by michalochman** [craftcms/anchors#5]
It is not possible to use anchors filter with tags containing their own anchor tags. The inserted anchor title does not strip HTML when creating default "Direct link to" anchor, pay attention to the `title` attribute.

e.g.:
```html
{{ '<h1>This does <a href="http://example.com/">not work</a> currently</h1>'|anchors }}
```
Is turned into this HTML:
```html
<a name="this-does-not-work-currently"></a>
<h1>This does <a href="http://example.com/">not work</a> currently <a class="anchor" href="#this-does-not-work-currently" title="Direct link to This does <a href=" http:="" example.com="" "="">not work</a> currently"&gt;#</h1>
```

**Comment by michalochman** [comment]
As a temporary solution it is enough to change the default `anchorLinkTitleText` to e.g. `'Direct link to {heading|striptags}'`:

```php
return [
    'anchorLinkTitleText' => 'Direct link to {heading|striptags}',
]
```

**Comment by brandonkelly** [comment]
Fixed - thanks!
