### ISSUE TITLE
Convert Issue

### ISSUE THREAD

**Issue by schellenbergk** [craftcms/anchors#6]
```
<h3 class="Tmp">
  <a href="http://testurl.com/" target="_blank">
    Test Link
  </a>
</h3>
```
the above gets converted to:

```
<a name="test-link"></a>

<h3 class="Tmp">
  <a href="http://testurl.com/" target="_blank">
    Test Link
  </a>
  <a "="" class="anchor" href="#test-link" http:="" target="_blank" title="Direct link to <a href=" testurl.com="">
    Test Link
  </a>
  ">#
</h3>
```

**Comment by schellenbergk** [comment]
Why in a first place does this plugin add "anchorLink"s?

**Comment by brandonkelly** [comment]
@MakeilaLundy guessing this bug exists for v1 and v2, and should be fixed for both. Given above code I think the expected HTML output should be:

```html
<a name="test-link"></a>

<h3 class="Tmp">
  <a href="http://testurl.com/" target="_blank">
    Test Link
  </a>

  <a class="anchor" href="#test-link" title="Direct link to Test Link"></a>
</h3>
```

**Comment by brandonkelly** [comment]
Probably just need to run the text inside the heading through [strip_tags()](http://php.net/manual/en/function.strip-tags.php).

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/anchors/commit/3f985cdd6b4754e2ae24d813353f12eaefaa3b93

**Comment by brandonkelly** [comment]
@MakeilaLundy v2 also needs to be updated with this fix.

**Comment by angrybrad** [comment]
@brandonkelly v2 already did it: https://github.com/craftcms/anchors/blob/v2/src/Parser.php#L113
