### ISSUE TITLE
Does it need to be a site request?

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/anchors#8]
The condition on [line 29 of Plugin.php](https://github.com/craftcms/anchors/blob/7c7e701a70ecf2caa9f4dc007b3d175fc7144780/src/Plugin.php#L29) requires that the extension is only available for site requests.

As it’s [not possible](https://github.com/twigphp/Twig/blob/69633fc19189699d20114f005efc8851c3fe9288/lib/Twig/ExtensionSet.php#L156) to register an extension after initialisation this is tripping me up whilst trying to render a template via the console interface.

> [ERROR] Unknown "anchors" filter.

Is there a reason why this cannot be available in all requests?

**Comment by brandonkelly** [comment]
That condition was mainly there to keep it away from Control Panel requests. I can specifically check for whether it’s a CP request though.

**Comment by brandonkelly** [comment]
Just released 2.1.1 with that change. (7fcc57e7b5ab09d931167e656ff346b36c94d5f3)
